# Host materialization of @proto_bazel_features's root BUILD: `:features` is depped by
# protobuf's bzl_libraries (bazel/private/BUILD).
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "features",
    srcs = ["features.bzl"],
    visibility = ["//visibility:public"],
)
