//! Deterministic-CBOR runtime conformance — exercised through the public API.
//!
//! The runtime (`cbor.rs`) is generated by `tautc --with-runtime`, so its own unit
//! tests don't survive regeneration; these live here, against `razel_wire`'s public
//! surface (`Cbor`/`encode`/`decode`), pinning the RFC 8949 subset razel freezes.

use razel_wire::{Cbor, decode, encode};

fn hex(v: &Cbor) -> String {
    encode(v).iter().map(|b| format!("{b:02x}")).collect()
}

#[test]
fn rfc8949_appendix_a_vectors() {
    // Canonical RFC 8949 Appendix A vectors for the frozen subset.
    assert_eq!(hex(&Cbor::Int(0)), "00");
    assert_eq!(hex(&Cbor::Int(1)), "01");
    assert_eq!(hex(&Cbor::Int(10)), "0a");
    assert_eq!(hex(&Cbor::Int(23)), "17");
    assert_eq!(hex(&Cbor::Int(24)), "1818");
    assert_eq!(hex(&Cbor::Int(100)), "1864");
    assert_eq!(hex(&Cbor::Int(1000)), "1903e8");
    assert_eq!(hex(&Cbor::Int(1_000_000)), "1a000f4240");
    assert_eq!(hex(&Cbor::Int(-1)), "20");
    assert_eq!(hex(&Cbor::Int(-100)), "3863");
    assert_eq!(hex(&Cbor::Text(String::new())), "60");
    assert_eq!(hex(&Cbor::Text("a".into())), "6161");
    assert_eq!(hex(&Cbor::Text("IETF".into())), "6449455446");
    assert_eq!(hex(&Cbor::Bytes(vec![])), "40");
    assert_eq!(hex(&Cbor::Bytes(vec![1, 2, 3, 4])), "4401020304");
    assert_eq!(hex(&Cbor::Bool(false)), "f4");
    assert_eq!(hex(&Cbor::Bool(true)), "f5");
    assert_eq!(hex(&Cbor::Null), "f6");
    assert_eq!(hex(&Cbor::Array(vec![])), "80");
    assert_eq!(
        hex(&Cbor::Array(vec![Cbor::Int(1), Cbor::Int(2), Cbor::Int(3)])),
        "83010203"
    );
    // map {1: 2} -> a1 01 02
    assert_eq!(hex(&Cbor::Map(vec![(1, Cbor::Int(2))])), "a10102");
}

#[test]
fn map_keys_are_emitted_ascending() {
    // Out-of-order entries must encode identically to sorted ones.
    let unsorted = Cbor::Map(vec![
        (3, Cbor::Int(30)),
        (1, Cbor::Int(10)),
        (2, Cbor::Int(20)),
    ]);
    let sorted = Cbor::Map(vec![
        (1, Cbor::Int(10)),
        (2, Cbor::Int(20)),
        (3, Cbor::Int(30)),
    ]);
    assert_eq!(encode(&unsorted), encode(&sorted));
    assert_eq!(hex(&sorted), "a3010a021403181e"); // {1:10, 2:20, 3:30}
}

#[test]
fn roundtrips_every_kind() {
    let values = vec![
        Cbor::Int(0),
        Cbor::Int(-42),
        Cbor::Int(1_000_000),
        Cbor::Text("héllo".into()),
        Cbor::Bytes(vec![0, 255, 128]),
        Cbor::Bool(true),
        Cbor::Bool(false),
        Cbor::Null,
        Cbor::Array(vec![Cbor::Int(1), Cbor::Text("x".into())]),
        Cbor::Map(vec![
            (1, Cbor::Text("a".into())),
            (2, Cbor::Array(vec![Cbor::Int(9)])),
        ]),
    ];
    for v in values {
        assert_eq!(decode(&encode(&v)), v, "roundtrip failed for {v:?}");
    }
}

#[test]
fn negative_int_boundaries() {
    assert_eq!(hex(&Cbor::Int(-24)), "37");
    assert_eq!(hex(&Cbor::Int(-25)), "3818");
    assert_eq!(
        decode(&encode(&Cbor::Int(i64::MIN + 1))),
        Cbor::Int(i64::MIN + 1)
    );
}
