"use strict";
// GENERATED server handler shape (implement these as a name->fn map):
//   build: (target) => ...
//   sync_file: (path, digest) => ...
//   version: () => ...
//   hello: (hello) => ...
//   run: (target, args) => ...
//   invocation.events: () => ...  // subscription (log)
//   affected: (files) => ...
//   build.subscribe: () => ...  // subscription (atom)
