load("@rules_rust//rust:defs.bzl", "rust_library", "rust_binary", "rust_test")

exports_files(["Cargo.toml"])  # crate_universe reads this

rust_library(
    name = "grazel_node",
    srcs = ["src/lib.rs"] + glob(["src/**/*.rs"], exclude = ["src/lib.rs"], allow_empty = True),
    crate_root = "src/lib.rs",
    edition = "2024",
    compile_data = glob(["**/*"], exclude = ["**/*.rs", "BUILD.bazel", "Cargo.toml"], allow_empty = True),
    deps = [],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "grazel_node_unit",
    crate = ":grazel_node",
    edition = "2024",
    compile_data = glob(["**/*"], exclude = ["**/*.rs", "BUILD.bazel", "Cargo.toml"], allow_empty = True),
)
