load("@rules_rust//rust:defs.bzl", "rust_library", "rust_binary", "rust_test")
load("@crates//:defs.bzl", "aliases", "all_crate_deps")

exports_files(["Cargo.toml"])  # crate_universe reads this

rust_library(
    name = "razel_conformance",
    srcs = ["src/lib.rs"] + glob(["src/**/*.rs"], exclude = ["src/lib.rs"] + ["src/bin/dashboard.rs"], allow_empty = True),
    crate_root = "src/lib.rs",
    edition = "2024",
    compile_data = glob(["**/*"], exclude = ["**/*.rs", "BUILD.bazel", "Cargo.toml"], allow_empty = True),
    aliases = aliases(),
    deps = all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
)

rust_binary(
    name = "dashboard",
    srcs = ["src/bin/dashboard.rs"],
    crate_root = "src/bin/dashboard.rs",
    edition = "2024",
    compile_data = glob(["**/*"], exclude = ["**/*.rs", "BUILD.bazel", "Cargo.toml"], allow_empty = True),
    aliases = aliases(),
    deps = all_crate_deps(normal = True) + [
        "//crates/razel-conformance:razel_conformance",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
)

rust_test(
    name = "razel_conformance_unit",
    crate = ":razel_conformance",
    edition = "2024",
    compile_data = glob(["**/*"], exclude = ["**/*.rs", "BUILD.bazel", "Cargo.toml"], allow_empty = True),
    deps = all_crate_deps(normal_dev = True),
)
